# Objective :- 

* A cancerous tumor is malignant, meaning it can grow and spread to other parts of the body. A benign tumor means the tumor can grow but will not spread.

* To Predict where the patient have Cancer or not 

# Step 1 :Library & Data Import

In [1]:
import os
import numpy as np
import pandas as pd
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data = pd.read_csv(r'Prostate_Cancer.csv')
data.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

#  Step 2 : Data Pre-Processing

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    object 
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


### Removing irrelevant  

In [4]:
data.drop('id',axis=1,inplace=True)

### Bad Rate Analysis 

In [5]:
data.diagnosis_result.value_counts()

M    62
B    38
Name: diagnosis_result, dtype: int64

# Step 3 : Data Partition

In [6]:
#Dividing data into train and test dataset
from sklearn.model_selection import train_test_split
#from random import seed

#seed(20)
train_x = data.drop(['diagnosis_result'],axis=1)
train_y = data['diagnosis_result']

# Train test split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3,random_state=20)

In [7]:
X_train.head()

radius  texture  perimeter  area  smoothness  compactness  symmetry  \
39      10       14         88   559       0.102        0.126     0.172   
64      16       19         83   499       0.112        0.126     0.191   
72      21       12        114   929       0.107        0.183     0.193   
60      15       18         65   312       0.113        0.081     0.274   
46      22       12         52   202       0.086        0.059     0.177   

    fractal_dimension  
39              0.064  
64              0.066  
72              0.065  
60              0.070  
46              0.065

#  Step 4 : Scaling Data

In [8]:
from sklearn.preprocessing import StandardScaler ,minmax_scale
scaler = StandardScaler()   # converting data into Z-scale = X-mean / Standard Deviation
#scaler.fit(X_train)         # Mean = 0 & standard Deviation =1

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train[0:5]

array([[-1.4759105 , -0.9576119 , -0.35386402, -0.43390083, -0.08072711,
        -0.12232371, -0.75012992, -0.1966181 ],
       [-0.19780244,  0.01670253, -0.56703512, -0.62177542,  0.67272588,
        -0.12232371, -0.13881081,  0.04697955],
       [ 0.86728761, -1.34733767,  0.75462568,  0.72465912,  0.29599939,
         0.80733651, -0.07446143, -0.07481928],
       [-0.41082045, -0.17816035, -1.33445106, -1.20731788,  0.74807118,
        -0.856266  ,  2.53168847,  0.53417484],
       [ 1.08030562, -1.34733767, -1.88869591, -1.55175463, -1.28625189,
        -1.21508223, -0.58925647, -0.07481928]])

In [10]:
X_train.mean(axis=0)

array([ 3.27119284e-16, -5.07530526e-17,  1.08048491e-16,  6.97854473e-17,
        1.60665132e-15, -1.38777878e-16, -1.05352235e-15,  8.03325660e-16])

In [11]:
 X_train.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

# Step 5 : Model Building 

In [12]:
# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=6)
## Fit the model on the training data.
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

# Step 6 : Predictions on Train Dataset

In [13]:
X_train=pd.DataFrame(X_train,columns=['radius', 'texture', 'perimeter', 'area','smoothness', 'compactness', 'symmetry', 'fractal_dimension'])
X_train.head()

radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0 -1.475910 -0.957612  -0.353864 -0.433901   -0.080727    -0.122324 -0.750130   
1 -0.197802  0.016703  -0.567035 -0.621775    0.672726    -0.122324 -0.138811   
2  0.867288 -1.347338   0.754626  0.724659    0.295999     0.807337 -0.074461   
3 -0.410820 -0.178160  -1.334451 -1.207318    0.748071    -0.856266  2.531688   
4  1.080306 -1.347338  -1.888696 -1.551755   -1.286252    -1.215082 -0.589256   

   fractal_dimension  
0          -0.196618  
1           0.046980  
2          -0.074819  
3           0.534175  
4          -0.074819

In [14]:
y_train.reset_index(drop=True, inplace=True)

In [15]:
train=pd.concat([X_train,y_train],axis=1)
train.head()

radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0 -1.475910 -0.957612  -0.353864 -0.433901   -0.080727    -0.122324 -0.750130   
1 -0.197802  0.016703  -0.567035 -0.621775    0.672726    -0.122324 -0.138811   
2  0.867288 -1.347338   0.754626  0.724659    0.295999     0.807337 -0.074461   
3 -0.410820 -0.178160  -1.334451 -1.207318    0.748071    -0.856266  2.531688   
4  1.080306 -1.347338  -1.888696 -1.551755   -1.286252    -1.215082 -0.589256   

   fractal_dimension diagnosis_result  
0          -0.196618                M  
1           0.046980                M  
2          -0.074819                M  
3           0.534175                B  
4          -0.074819                B

In [16]:
train['Predicted']=model.predict(X_train)
train.head()

C:\Users\L\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0 -1.475910 -0.957612  -0.353864 -0.433901   -0.080727    -0.122324 -0.750130   
1 -0.197802  0.016703  -0.567035 -0.621775    0.672726    -0.122324 -0.138811   
2  0.867288 -1.347338   0.754626  0.724659    0.295999     0.807337 -0.074461   
3 -0.410820 -0.178160  -1.334451 -1.207318    0.748071    -0.856266  2.531688   
4  1.080306 -1.347338  -1.888696 -1.551755   -1.286252    -1.215082 -0.589256   

   fractal_dimension diagnosis_result Predicted  
0          -0.196618                M         M  
1           0.046980                M         M  
2          -0.074819                M         M  
3           0.534175                B         B  
4          -0.074819                B         B

# Step 7 : Model Performance Metrics

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(train['diagnosis_result'],train['Predicted'])
print(confusion_matrix)

[[17  4]
 [ 2 47]]


In [18]:
Accuracy_Train=((16+48)/(70)*100)
print(Accuracy_Train)

91.42857142857143


In [19]:
from sklearn.metrics import classification_report
print(classification_report(train['diagnosis_result'], train['Predicted']))

              precision    recall  f1-score   support

           B       0.89      0.81      0.85        21
           M       0.92      0.96      0.94        49

    accuracy                           0.91        70
   macro avg       0.91      0.88      0.90        70
weighted avg       0.91      0.91      0.91        70



# Step 8 : Predictions on Test Dataset

In [20]:
X_test=pd.DataFrame(X_test,columns=['radius', 'texture', 'perimeter', 'area','smoothness', 'compactness', 'symmetry', 'fractal_dimension'])
X_test.head()

radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.867288 -0.178160   1.180968  1.354039   -0.984871    -0.497450 -1.200576   
1  0.228234 -1.152475  -0.737572 -0.709450   -0.834180    -1.068294 -0.750130   
2  0.867288  1.575606   1.436773  1.582620    1.652215     0.432210  0.375984   
3 -1.475910 -0.762749  -0.481767 -0.518444   -0.457454    -0.464830 -0.653606   
4 -1.475910  0.016703   1.266236  1.422926    0.145309    -0.106014 -0.106636   

   fractal_dimension  
0          -1.292808  
1          -0.805612  
2          -0.683813  
3          -0.440216  
4          -0.683813

In [21]:
y_test.reset_index(drop=True, inplace=True)

In [22]:
test=pd.concat([X_test,y_test],axis=1)
test.head()

radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.867288 -0.178160   1.180968  1.354039   -0.984871    -0.497450 -1.200576   
1  0.228234 -1.152475  -0.737572 -0.709450   -0.834180    -1.068294 -0.750130   
2  0.867288  1.575606   1.436773  1.582620    1.652215     0.432210  0.375984   
3 -1.475910 -0.762749  -0.481767 -0.518444   -0.457454    -0.464830 -0.653606   
4 -1.475910  0.016703   1.266236  1.422926    0.145309    -0.106014 -0.106636   

   fractal_dimension diagnosis_result  
0          -1.292808                M  
1          -0.805612                B  
2          -0.683813                M  
3          -0.440216                M  
4          -0.683813                M

In [23]:
test['Predicted']=model.predict(X_test)
test.head()

C:\Users\L\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


radius   texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.867288 -0.178160   1.180968  1.354039   -0.984871    -0.497450 -1.200576   
1  0.228234 -1.152475  -0.737572 -0.709450   -0.834180    -1.068294 -0.750130   
2  0.867288  1.575606   1.436773  1.582620    1.652215     0.432210  0.375984   
3 -1.475910 -0.762749  -0.481767 -0.518444   -0.457454    -0.464830 -0.653606   
4 -1.475910  0.016703   1.266236  1.422926    0.145309    -0.106014 -0.106636   

   fractal_dimension diagnosis_result Predicted  
0          -1.292808                M         M  
1          -0.805612                B         B  
2          -0.683813                M         M  
3          -0.440216                M         B  
4          -0.683813                M         M

# Step 9 : Model Performance Metrics on Test data 

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['diagnosis_result'],test['Predicted'])
print(confusion_matrix)

[[13  4]
 [ 2 11]]


In [25]:
Accuracy_test=((10+13)/(30)*100)
Accuracy_test

76.66666666666667

In [26]:
from sklearn.metrics import classification_report
print(classification_report(test['diagnosis_result'], test['Predicted']))

              precision    recall  f1-score   support

           B       0.87      0.76      0.81        17
           M       0.73      0.85      0.79        13

    accuracy                           0.80        30
   macro avg       0.80      0.81      0.80        30
weighted avg       0.81      0.80      0.80        30



# Cross Validation Method  - Random concept

* To identify the best value of K

In [27]:
from sklearn.metrics import accuracy_score
for K in range(25):
    K_value = K+1
    model2 = KNeighborsClassifier(n_neighbors = K_value)
    model2.fit(X_train, y_train) 
    y_pred_Train= model2.predict(X_train)
    y_pred_test = model2.predict(X_test)
    print("Train Accuracy is ", 
          round(accuracy_score(y_train,y_pred_Train)*100,0), "      ","Test Accuracy is ", round(accuracy_score(y_test,y_pred_test)*100,0),"% for K-Value:",
          K_value)

Train Accuracy is  100.0        Test Accuracy is  73.0 % for K-Value: 1
Train Accuracy is  87.0        Test Accuracy is  77.0 % for K-Value: 2
Train Accuracy is  90.0        Test Accuracy is  77.0 % for K-Value: 3
Train Accuracy is  89.0        Test Accuracy is  83.0 % for K-Value: 4
Train Accuracy is  90.0        Test Accuracy is  73.0 % for K-Value: 5
Train Accuracy is  91.0        Test Accuracy is  80.0 % for K-Value: 6
Train Accuracy is  91.0        Test Accuracy is  77.0 % for K-Value: 7
Train Accuracy is  90.0        Test Accuracy is  87.0 % for K-Value: 8
Train Accuracy is  89.0        Test Accuracy is  80.0 % for K-Value: 9
Train Accuracy is  90.0        Test Accuracy is  80.0 % for K-Value: 10
Train Accuracy is  89.0        Test Accuracy is  73.0 % for K-Value: 11
Train Accuracy is  89.0        Test Accuracy is  73.0 % for K-Value: 12
Train Accuracy is  87.0        Test Accuracy is  70.0 % for K-Value: 13
Train Accuracy is  87.0        Test Accuracy is  73.0 % for K-Value: 14


# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=8,metric='euclidean')
## Fit the model on the training data.
model.fit(X_train, y_train)

In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': np.arange(1, 9)}


knn2 = KNeighborsClassifier()
knn_gscv = GridSearchCV(knn2, 
                        param_grid,
                        cv=10,
                        verbose=1)
knn_gscv.fit(X_train, y_train)

Fitting 10 folds for each of 8 candidates, totalling 80 fits


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8])},
             verbose=1)

In [29]:
#check top performing n_neighbors value
knn_gscv.best_params_

{'n_neighbors': 6}

In [30]:
knn_gscv.best_score_

0.8857142857142856

# Finish