# Step 1 :Library & Data Import

In [33]:
import os
import numpy as np
import pandas as pd
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [34]:
data = pd.read_csv(r'Fish_dataset.csv')
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

#  Step 2 : Data Pre-Processing

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


# Step 3 : Data Partition

In [36]:
#Dividing data into train and test dataset
from sklearn.model_selection import train_test_split
#from random import seed

#seed(20)
train_x = data.drop(['Species'],axis=1)
train_y = data['Species']

# Train test split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3,random_state=20)

In [37]:
X_train.head()

Weight  Length1  Length2  Length3   Height   Width
140   950.0     48.3     51.7     55.1   8.9262  6.1712
37     78.0     17.5     18.8     21.2   5.5756  2.9044
65    150.0     18.4     20.0     22.4   8.8928  3.2928
72      5.9      7.5      8.4      8.8   2.1120  1.4080
2     340.0     23.9     26.5     31.1  12.3778  4.6961

#  Step 4 : Scaling Data

In [38]:
from sklearn.preprocessing import StandardScaler ,minmax_scale
scaler = StandardScaler()   # converting data into Z-scale = X-mean / Standard Deviation
#scaler.fit(X_train)         # Mean = 0 & standard Deviation =1

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
X_train[0:5]

array([[ 1.51367367e+00,  2.18165034e+00,  2.14370121e+00,
         2.01357047e+00, -2.28658608e-02,  1.03179267e+00],
       [-8.90499285e-01, -8.37425226e-01, -8.57595544e-01,
        -8.28464159e-01, -7.68886985e-01, -8.57646248e-01],
       [-6.91989591e-01, -7.49205485e-01, -7.48125753e-01,
        -7.27861164e-01, -3.03024708e-02, -6.33004985e-01],
       [-1.08928469e+00, -1.81764457e+00, -1.80633373e+00,
        -1.86802845e+00, -1.54006790e+00, -1.72312819e+00],
       [-1.68144566e-01, -2.10084848e-01, -1.55164388e-01,
         1.51055549e-03,  7.45643216e-01,  1.78630144e-01]])

In [40]:
X_train.mean(axis=0)

array([-7.10142655e-17, -3.12562788e-16, -4.95099457e-17,  5.32106891e-16,
       -2.65053245e-16,  8.65173798e-17])

In [41]:
 X_train.std(axis=0)

array([1., 1., 1., 1., 1., 1.])

# Step 5 : Model Building 

In [42]:
# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=6)
## Fit the model on the training data.
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

# Step 6 : Predictions on Train Dataset


In [43]:
X_train=pd.DataFrame(X_train,columns=['Weight','Length1','Length2','Length3','Height','Width'])
X_train.head()

Weight   Length1   Length2   Length3    Height     Width
0  1.513674  2.181650  2.143701  2.013570 -0.022866  1.031793
1 -0.890499 -0.837425 -0.857596 -0.828464 -0.768887 -0.857646
2 -0.691990 -0.749205 -0.748126 -0.727861 -0.030302 -0.633005
3 -1.089285 -1.817645 -1.806334 -1.868028 -1.540068 -1.723128
4 -0.168145 -0.210085 -0.155164  0.001511  0.745643  0.178630

In [44]:
y_train.reset_index(drop=True, inplace=True)

In [45]:
train=pd.concat([X_train,y_train],axis=1)
train.head()

Weight   Length1   Length2   Length3    Height     Width Species
0  1.513674  2.181650  2.143701  2.013570 -0.022866  1.031793    Pike
1 -0.890499 -0.837425 -0.857596 -0.828464 -0.768887 -0.857646   Roach
2 -0.691990 -0.749205 -0.748126 -0.727861 -0.030302 -0.633005  Parkki
3 -1.089285 -1.817645 -1.806334 -1.868028 -1.540068 -1.723128   Perch
4 -0.168145 -0.210085 -0.155164  0.001511  0.745643  0.178630   Bream

In [46]:
train['Predicted']=model.predict(X_train)
train.head()

C:\Users\L\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


Weight   Length1   Length2   Length3    Height     Width Species  \
0  1.513674  2.181650  2.143701  2.013570 -0.022866  1.031793    Pike   
1 -0.890499 -0.837425 -0.857596 -0.828464 -0.768887 -0.857646   Roach   
2 -0.691990 -0.749205 -0.748126 -0.727861 -0.030302 -0.633005  Parkki   
3 -1.089285 -1.817645 -1.806334 -1.868028 -1.540068 -1.723128   Perch   
4 -0.168145 -0.210085 -0.155164  0.001511  0.745643  0.178630   Bream   

  Predicted  
0      Pike  
1     Perch  
2    Parkki  
3     Smelt  
4     Bream

# Step 7 : Model Performance Metrics

In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(train['Species'],train['Predicted'])
print(confusion_matrix)

[[26  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0 32  0  1  1  0]
 [ 0  0  1 11  0  0  0]
 [ 1  0  9  0  5  0  0]
 [ 0  0  0  0  0 12  0]
 [ 0  0  4  0  0  0  0]]


In [48]:
Accuracy_Train=((26+8+32+11+5+12)/(111)*100)
print(Accuracy_Train)

84.68468468468468


In [49]:
from sklearn.metrics import classification_report
print(classification_report(train['Species'], train['Predicted']))

              precision    recall  f1-score   support

       Bream       0.96      1.00      0.98        26
      Parkki       1.00      1.00      1.00         8
       Perch       0.70      0.94      0.80        34
        Pike       1.00      0.92      0.96        12
       Roach       0.83      0.33      0.48        15
       Smelt       0.92      1.00      0.96        12
   Whitefish       0.00      0.00      0.00         4

    accuracy                           0.85       111
   macro avg       0.77      0.74      0.74       111
weighted avg       0.83      0.85      0.82       111



C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Step 8 : Predictions on Test Dataset

In [50]:


X_test=pd.DataFrame(X_test,columns=['Weight','Length1','Length2','Length3','Height','Width'])
X_test.head()

Weight   Length1   Length2   Length3    Height     Width
0 -1.086252 -1.562788 -1.605639 -1.633288 -1.625478 -1.873275
1 -0.261885 -0.043448 -0.018327 -0.023640 -0.055863  0.170244
2 -0.587221 -0.337513 -0.328492 -0.409285 -0.511099 -0.128083
3 -0.747131 -0.592370 -0.565676 -0.635642 -0.649901 -0.498706
4  0.300559  1.368068  1.304433  1.208747 -0.490704  0.041497

In [51]:
y_test.reset_index(drop=True, inplace=True)

In [52]:
test=pd.concat([X_test,y_test],axis=1)
test.head()

Weight   Length1   Length2   Length3    Height     Width    Species
0 -1.086252 -1.562788 -1.605639 -1.633288 -1.625478 -1.873275      Smelt
1 -0.261885 -0.043448 -0.018327 -0.023640 -0.055863  0.170244  Whitefish
2 -0.587221 -0.337513 -0.328492 -0.409285 -0.511099 -0.128083      Perch
3 -0.747131 -0.592370 -0.565676 -0.635642 -0.649901 -0.498706      Perch
4  0.300559  1.368068  1.304433  1.208747 -0.490704  0.041497       Pike

In [53]:
test['Predicted']=model.predict(X_test)
test.head()

C:\Users\L\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


Weight   Length1   Length2   Length3    Height     Width    Species  \
0 -1.086252 -1.562788 -1.605639 -1.633288 -1.625478 -1.873275      Smelt   
1 -0.261885 -0.043448 -0.018327 -0.023640 -0.055863  0.170244  Whitefish   
2 -0.587221 -0.337513 -0.328492 -0.409285 -0.511099 -0.128083      Perch   
3 -0.747131 -0.592370 -0.565676 -0.635642 -0.649901 -0.498706      Perch   
4  0.300559  1.368068  1.304433  1.208747 -0.490704  0.041497       Pike   

  Predicted  
0     Smelt  
1     Perch  
2     Perch  
3     Perch  
4      Pike

# Step 9 : Model Performance Metrics on Test data 

In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['Species'],test['Predicted'])
print(confusion_matrix)

[[ 8  1  0  0  0  0  0]
 [ 0  2  0  0  1  0  0]
 [ 0  0 20  0  1  1  0]
 [ 0  0  0  5  0  0  0]
 [ 0  1  3  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  2  0  0  0  0]]


In [55]:
Accuracy_test=((8+2+20+5+1+2)/(50)*100)
Accuracy_test

76.0

In [56]:
from sklearn.metrics import classification_report
print(classification_report(test['Species'], test['Predicted']))

              precision    recall  f1-score   support

       Bream       1.00      0.89      0.94         9
      Parkki       0.50      0.67      0.57         3
       Perch       0.80      0.91      0.85        22
        Pike       1.00      1.00      1.00         5
       Roach       0.33      0.20      0.25         5
       Smelt       0.67      1.00      0.80         2
   Whitefish       0.00      0.00      0.00         2

    accuracy                           0.79        48
   macro avg       0.61      0.67      0.63        48
weighted avg       0.75      0.79      0.77        48



C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\L\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Cross Validation Method  - Random concept


* To identify the best value of K

In [57]:
from sklearn.metrics import accuracy_score
for K in range(25):
    K_value = K+1
    model2 = KNeighborsClassifier(n_neighbors = K_value)
    model2.fit(X_train, y_train) 
    y_pred_Train= model2.predict(X_train)
    y_pred_test = model2.predict(X_test)
    print("Train Accuracy is ", 
          round(accuracy_score(y_train,y_pred_Train)*100,0), "      ","Test Accuracy is ", round(accuracy_score(y_test,y_pred_test)*100,0),"% for K-Value:",
          K_value)

Train Accuracy is  100.0        Test Accuracy is  83.0 % for K-Value: 1
Train Accuracy is  90.0        Test Accuracy is  77.0 % for K-Value: 2
Train Accuracy is  90.0        Test Accuracy is  75.0 % for K-Value: 3
Train Accuracy is  87.0        Test Accuracy is  77.0 % for K-Value: 4
Train Accuracy is  85.0        Test Accuracy is  81.0 % for K-Value: 5
Train Accuracy is  85.0        Test Accuracy is  79.0 % for K-Value: 6
Train Accuracy is  84.0        Test Accuracy is  75.0 % for K-Value: 7
Train Accuracy is  83.0        Test Accuracy is  71.0 % for K-Value: 8
Train Accuracy is  80.0        Test Accuracy is  69.0 % for K-Value: 9
Train Accuracy is  79.0        Test Accuracy is  73.0 % for K-Value: 10
Train Accuracy is  78.0        Test Accuracy is  73.0 % for K-Value: 11
Train Accuracy is  75.0        Test Accuracy is  75.0 % for K-Value: 12
Train Accuracy is  72.0        Test Accuracy is  75.0 % for K-Value: 13
Train Accuracy is  73.0        Test Accuracy is  77.0 % for K-Value: 14


# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=8,metric='euclidean')
## Fit the model on the training data.
model.fit(X_train, y_train)

In [58]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': np.arange(1, 9)}


knn2 = KNeighborsClassifier()
knn_gscv = GridSearchCV(knn2, 
                        param_grid,
                        cv=10,
                        verbose=1)
knn_gscv.fit(X_train, y_train)

Fitting 10 folds for each of 8 candidates, totalling 80 fits


C:\Users\L\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8])},
             verbose=1)

In [60]:
knn_gscv.best_params_
##check top performing n_neighbors value


{'n_neighbors': 2}

In [61]:
knn_gscv.best_score_

0.8121212121212121

# Finish