# Step 1 : -Data import & library

In [1]:
%matplotlib inline  
# To make data visualisations display in Jupyter Notebooks 
import numpy as np   # linear algebra
import pandas as pd  # Data processing, Input & Output load
import matplotlib.pyplot as plt # Visuvalization & plotting
import datetime  
from sklearn.svm import SVC  # supervised learning methods used for classification, regression 
import joblib  #Joblib is a set of tools to provide lightweight pipelining in Python (Avoid computing twice the same thing)

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
                                    # GridSearchCV - Implements a “fit” and a “score” method
                                    # train_test_split - Split arrays or matrices into random train and test subsets
                                    # cross_val_score - Evaluate a score by cross-validation
from sklearn.metrics import f1_score, roc_auc_score, recall_score, precision_score, make_scorer, accuracy_score, roc_curve, confusion_matrix, classification_report
                                    # Differnt metrics to evaluate the model 
import warnings   # To avoid warning messages in the code run
warnings.filterwarnings("ignore")

import seaborn as sn
import matplotlib.cm as cm
from matplotlib.colors import ListedColormap, BoundaryNorm
from sklearn import neighbors
import matplotlib.patches as mpatches
import graphviz
from sklearn.tree import export_graphviz
import matplotlib.patches as mpatches
from PIL import  Image
import seaborn as sns#visualization
import io
import plotly.offline as py#visualization
py.init_notebook_mode(connected=True)#visualization
import plotly.graph_objs as go#visualization
import plotly.tools as tls#visualization
import plotly.figure_factory as ff#visualization

In [10]:
import os 
os.chdir(r"C:\Users\USER\Desktop\Python Code\SVM") 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\USER\\Desktop\\Python Code\\SVM'

In [2]:
data=pd.read_csv(r"Credit_Card (2).csv")

In [3]:
data.head()

fgood  cbinq  cbline  cbterm   cblineut  cbtob cbdpd cbnew pmt  tob     dpd  \
0    No      2       2       0  47.513611      5    No    No   M    2  Medium   
1    No      2       2       2  52.362223      4    No    No   A    1    High   
2    No      2       2       0  35.896405      5    No   Yes   M    2    High   
3    No      2       3       1  41.935781      6    No    No   P    4  Medium   
4    No      0       1       0  44.236619      5    No    No   P    4  Medium   

        dep  dc  od home  dd online      period  
0  10481.40  20   1   No   0    Yes   3/31/2018  
1  10182.43  17   1   No   0    Yes   5/31/2018  
2   9645.37  23   0   No   0    Yes   7/31/2018  
3  13702.76  31   1   No   0    Yes  12/31/2017  
4  18720.09  26   2  Yes   1    Yes   2/28/2018

# Step 2 : - Data Pre-Processing



## Data Structure or type 

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   fgood     2500 non-null   object 
 1   cbinq     2500 non-null   int64  
 2   cbline    2500 non-null   int64  
 3   cbterm    2500 non-null   int64  
 4   cblineut  2500 non-null   float64
 5   cbtob     2500 non-null   int64  
 6   cbdpd     2500 non-null   object 
 7   cbnew     2500 non-null   object 
 8   pmt       2500 non-null   object 
 9   tob       2500 non-null   int64  
 10  dpd       2500 non-null   object 
 11  dep       2500 non-null   float64
 12  dc        2500 non-null   int64  
 13  od        2500 non-null   int64  
 14  home      2500 non-null   object 
 15  dd        2500 non-null   int64  
 16  online    2500 non-null   object 
 17  period    2500 non-null   object 
dtypes: float64(2), int64(8), object(8)
memory usage: 351.7+ KB


## Checking Missing Value

In [5]:
data.isna().sum()

fgood       0
cbinq       0
cbline      0
cbterm      0
cblineut    0
cbtob       0
cbdpd       0
cbnew       0
pmt         0
tob         0
dpd         0
dep         0
dc          0
od          0
home        0
dd          0
online      0
period      0
dtype: int64

## Removing Irrelavent Variable

In [6]:
data=data.drop(['period'],axis=1)

## Behaviour of data

In [7]:
data.describe()

cbinq       cbline       cbterm     cblineut        cbtob  \
count  2500.000000  2500.000000  2500.000000  2500.000000  2500.000000   
mean      1.060000     1.741600     0.491600    42.814251     5.623600   
std       0.678664     1.162484     0.590312    13.265830     1.308819   
min       0.000000     0.000000     0.000000     0.000000     3.000000   
25%       1.000000     1.000000     0.000000    34.196802     5.000000   
50%       1.000000     2.000000     0.000000    42.564905     6.000000   
75%       2.000000     2.000000     1.000000    51.663069     7.000000   
max       2.000000     5.000000     2.000000    91.596578     8.000000   

               tob           dep           dc           od           dd  
count  2500.000000   2500.000000  2500.000000  2500.000000  2500.000000  
mean      2.793200  12076.991264    22.098000     0.642400     0.678400  
std       1.416487   3163.988922     5.161691     0.834027     0.728276  
min       0.000000   1598.290000     4.000000     0.000000     0.000000  
25%       2.000000  10013.922500    19.000000     0.000000     0.000000  
50%       3.000000  12106.595000    22.000000     0.000000     1.000000  
75%       4.000000  14254.487500    26.000000     1.000000     1.000000  
max       5.000000  25000.000000    45.000000     2.000000     2.000000

In [8]:
data.describe(include="object")

fgood cbdpd cbnew   pmt     dpd  home online
count   2500  2500  2500  2500    2500  2500   2500
unique     2     2     2     3       3     2      2
top       No    No    No     M  Medium    No    Yes
freq    2000  2153  2097  1177    1571  1734   1624

## Taking subset data of Number 

In [9]:
data.head()

fgood  cbinq  cbline  cbterm   cblineut  cbtob cbdpd cbnew pmt  tob     dpd  \
0    No      2       2       0  47.513611      5    No    No   M    2  Medium   
1    No      2       2       2  52.362223      4    No    No   A    1    High   
2    No      2       2       0  35.896405      5    No   Yes   M    2    High   
3    No      2       3       1  41.935781      6    No    No   P    4  Medium   
4    No      0       1       0  44.236619      5    No    No   P    4  Medium   

        dep  dc  od home  dd online  
0  10481.40  20   1   No   0    Yes  
1  10182.43  17   1   No   0    Yes  
2   9645.37  23   0   No   0    Yes  
3  13702.76  31   1   No   0    Yes  
4  18720.09  26   2  Yes   1    Yes

In [10]:
# #Employee Numeric columns
data_num = data[data.select_dtypes(include=[np.number]).columns.tolist()]
data_num.head(3)

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd
0      2       2       0  47.513611      5    2  10481.40  20   1   0
1      2       2       2  52.362223      4    1  10182.43  17   1   0
2      2       2       0  35.896405      5    2   9645.37  23   0   0

## Taking subset data of Category 

In [11]:
# #Employee Numeric columns
data_cat = data[data.select_dtypes(include=['object']).columns.tolist()]
data_cat.head(3)

fgood cbdpd cbnew pmt     dpd home online
0    No    No    No   M  Medium   No    Yes
1    No    No    No   A    High   No    Yes
2    No    No   Yes   M    High   No    Yes

## Converting Quality Variable to Number

In [12]:
from sklearn.preprocessing import LabelEncoder
data_cat=data_cat.apply(LabelEncoder().fit_transform)
data_cat.head(3)

fgood  cbdpd  cbnew  pmt  dpd  home  online
0      0      0      0    1    2     0       1
1      0      0      0    0    0     0       1
2      0      0      1    1    0     0       1

## Combine to Dataset

In [13]:
data_combined = pd.concat([data_num, data_cat],axis=1)

In [14]:
data_combined.head()

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd  fgood  \
0      2       2       0  47.513611      5    2  10481.40  20   1   0      0   
1      2       2       2  52.362223      4    1  10182.43  17   1   0      0   
2      2       2       0  35.896405      5    2   9645.37  23   0   0      0   
3      2       3       1  41.935781      6    4  13702.76  31   1   0      0   
4      0       1       0  44.236619      5    4  18720.09  26   2   1      0   

   cbdpd  cbnew  pmt  dpd  home  online  
0      0      0    1    2     0       1  
1      0      0    0    0     0       1  
2      0      1    1    0     0       1  
3      0      0    2    2     0       1  
4      0      0    2    2     1       1

# Step 3 :  - Data Visualization

#### Bad Rate Analysis 

In [15]:
import plotly.express as px

fig = px.pie(data,names='fgood',color='fgood',
             color_discrete_map={'Yes':'red',
                                 'No':'green'})
fig.show()

#### Trend Analysis 

In [26]:
#Separating churn and non churn customers
bad  = data[data["fgood"] == "Yes"] #default ( Bad )
bad

fgood  cbinq  cbline  cbterm   cblineut  cbtob cbdpd cbnew pmt  tob  \
2000   Yes      0       0       1  43.916189      5    No    No   A    3   
2001   Yes      2       4       1  66.554611      4   Yes    No   M    0   
2002   Yes      1       3       2  61.836908      5   Yes    No   M    1   
2003   Yes      1       3       1  41.829239      4    No    No   A    2   
2004   Yes      2       2       0  28.121699      5    No    No   M    1   
...    ...    ...     ...     ...        ...    ...   ...   ...  ..  ...   
2495   Yes      1       2       0  26.864484      6    No    No   M    2   
2496   Yes      0       3       1  31.066761      6    No    No   M    2   
2497   Yes      2       1       1  51.117910      4    No   Yes   M    5   
2498   Yes      1       2       1  43.856574      5   Yes   Yes   M    3   
2499   Yes      0       2       2  40.706101      5    No    No   P    5   

         dpd       dep  dc  od home  dd online  
2000  Medium   7667.02  18   0  Yes   2     No  
2001    High   5586.31  10   2   No   0    Yes  
2002    High   5865.09  16   2   No   0    Yes  
2003    High  11249.78  23   2   No   0    Yes  
2004  Medium   9995.30  18   1   No   0     No  
...      ...       ...  ..  ..  ...  ..    ...  
2495     Low  12853.50  23   0  Yes   0    Yes  
2496  Medium   8374.44  22   0   No   1     No  
2497     Low   6722.98  22   2   No   2    Yes  
2498    High  11851.76  21   2   No   1     No  
2499  Medium  15183.60  25   0  Yes   1     No  

[500 rows x 17 columns]

In [27]:
import plotly.express as px

fig = px.sunburst(bad, path=["pmt",'home',"dpd", "online"])  # subset data = default
fig.show()

# Conclusion
Customer which are Most influening the bad 

payment method = "manually"
online = "Yes"
home = "No"

# Step 4: Data Partition

In [19]:
#Dividing data into train and test dataset
from sklearn.model_selection import train_test_split
#from random import seed

#seed(20)
x = data_combined.drop(['fgood'],axis=1)  # fgood 
y = data_combined['fgood']

# Train test split

X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.3,random_state=231)

# Step 5:Modelling with GridSearch

# Define Model parameters to tune
model_parameters = {
        'kernel':['linear'], # calculation
        'C':[1, 10], #cost complexity or penalty 
        'gamma': [0.0001]
    }

# Gridsearch the parameters to find the best parameters. 
model = SVC(probability=True)  # Support vector classifier 

gscv = GridSearchCV(estimator=model, 
                    param_grid=model_parameters, 
                    cv=5,  # times 
                    verbose=1, 
                    n_jobs=-1,
                    scoring='accuracy')

gscv.fit(X_train, y_train)

print('The best parameter are -', gscv.best_params_)

# Re-fit the model with the best parameters
final_model = SVC(**gscv.best_params_)
final_model.fit(X_train, y_train)

# Manual Model 

In [20]:
from sklearn.svm import SVC
#from sklearn.svm import LinearSVC
model = SVC(kernel="linear")  # if we use linear then only we get support_vector
model.fit(X_train, y_train) #Variable = fgood ( defaulter =1 , non-defaulter = 0)

SVC(kernel='linear')

In [21]:
model.support_vectors_        #####this are support vector

array([[1., 2., 0., ..., 2., 1., 1.],
       [1., 3., 0., ..., 1., 0., 1.],
       [1., 1., 0., ..., 2., 1., 1.],
       ...,
       [2., 5., 2., ..., 0., 0., 1.],
       [2., 3., 0., ..., 0., 0., 1.],
       [1., 2., 0., ..., 0., 0., 1.]])

In [22]:
np.round(model.coef_)                 ######### Coefficient value   ( beta's value)

array([[  9.,   4.,  -0.,  -0.,  -5., -14.,  -0.,  -2.,   7., -10.,  -1.,
          3.,   4., -18., -17.,  -2.]])

In [23]:
np.round(model.intercept_)   ###### bias  ( intercept`)

array([171.])

# Step 6 : Predictions on Train Dataset

In [36]:
train=pd.concat([X_train,y_train],axis=1)
train.head()

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd  \
602       1       2       0  49.713864      6    2  12659.39  30   0   0   
1930      1       2       1  41.613240      5    4  11944.49  23   2   1   
226       1       2       0  44.787702      7    2  13165.77  18   1   0   
313       1       2       0  54.390238      5    3  14681.01  24   1   1   
852       1       2       0  31.976966      5    0  11921.57  17   0   2   

      cbdpd  cbnew  pmt  dpd  home  online  fgood  
602       0      0    0    2     0       1      0  
1930      0      0    1    2     1       0      0  
226       0      0    1    0     0       1      0  
313       1      0    0    0     1       1      0  
852       0      0    1    2     1       1      0

In [37]:
train['Prediction']=model.predict(X_train)
train.head()

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd  \
602       1       2       0  49.713864      6    2  12659.39  30   0   0   
1930      1       2       1  41.613240      5    4  11944.49  23   2   1   
226       1       2       0  44.787702      7    2  13165.77  18   1   0   
313       1       2       0  54.390238      5    3  14681.01  24   1   1   
852       1       2       0  31.976966      5    0  11921.57  17   0   2   

      cbdpd  cbnew  pmt  dpd  home  online  fgood  Prediction  
602       0      0    0    2     0       1      0           0  
1930      0      0    1    2     1       0      0           0  
226       0      0    1    0     0       1      0           0  
313       1      0    0    0     1       1      0           0  
852       0      0    1    2     1       1      0           0

# Step 7 : Model Performance Metrics

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(train['Prediction'],train['fgood'])
print(confusion_matrix)

[[1336  244]
 [  64  106]]


In [27]:
Accuracy_Train=((1336+106)/(1750)*100)
print(Accuracy_Train)

82.39999999999999


In [39]:
from sklearn.metrics import classification_report
print(classification_report(train['fgood'], train['Prediction']))

              precision    recall  f1-score   support

           0       0.85      0.95      0.90      1400
           1       0.62      0.30      0.41       350

    accuracy                           0.82      1750
   macro avg       0.73      0.63      0.65      1750
weighted avg       0.80      0.82      0.80      1750



* Model is Good fit on Train dataset

# Step 8 : Predictions on Test Dataset

In [40]:
test=pd.concat([X_test,y_test],axis=1)
test.head()

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd  \
1686      1       1       1  44.878464      7    3   5392.92  30   0   1   
595       1       2       0  39.507725      6    5  15864.43  23   0   1   
896       2       1       0  46.448983      5    5  10179.37  26   2   2   
455       0       0       0  28.162747      7    2  11860.68  25   0   0   
121       1       1       1  32.127723      5    4  17495.40  21   0   0   

      cbdpd  cbnew  pmt  dpd  home  online  fgood  
1686      0      0    2    1     0       0      0  
595       0      0    0    1     1       0      0  
896       0      0    1    2     0       0      0  
455       0      0    0    2     0       0      0  
121       0      0    0    2     1       1      0

In [41]:
test['Prediction']=model.predict(X_test)
test.head()

cbinq  cbline  cbterm   cblineut  cbtob  tob       dep  dc  od  dd  \
1686      1       1       1  44.878464      7    3   5392.92  30   0   1   
595       1       2       0  39.507725      6    5  15864.43  23   0   1   
896       2       1       0  46.448983      5    5  10179.37  26   2   2   
455       0       0       0  28.162747      7    2  11860.68  25   0   0   
121       1       1       1  32.127723      5    4  17495.40  21   0   0   

      cbdpd  cbnew  pmt  dpd  home  online  fgood  Prediction  
1686      0      0    2    1     0       0      0           0  
595       0      0    0    1     1       0      0           0  
896       0      0    1    2     0       0      0           0  
455       0      0    0    2     0       0      0           0  
121       0      0    0    2     1       1      0           0

# Step 9 : Model Performance Metrics on Test data 

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix( test['Predicted'],test['fgood'])
print(confusion_matrix)

[[574  99]
 [ 26  51]]


In [32]:
Accuracy_test=((574+51)/(750)*100)
Accuracy_test

83.33333333333334

In [42]:
print(classification_report(test['fgood'], test['Prediction']))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90       600
           1       0.66      0.34      0.45       150

    accuracy                           0.83       750
   macro avg       0.76      0.65      0.68       750
weighted avg       0.81      0.83      0.81       750



* Model Performance on Test dataset is also good fit 

# Finished